# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
#source 'https://github.com/CocoaPods/Specs.git'

target 'GXConfigTableViewVCSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings! #抑制所有的警告!
  
  # table/collection快速注册cell扩展
  pod 'Reusable'
  # RAC
  pod 'RxCocoa'

end

#Pods config
#Fix Xcode14 Bundle target error
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_BITCODE'] = "NO"
    end
  end
end
